spring.application.name=MilletMother
spring.data.mongodb.uri=mongodb+srv://milletAdmin:MilletMother2025@milletmothercluster.ozeqtg7.mongodb.net/CollegeDB?retryWrites=true&w=majority&appName=MilletMotherCluster
